name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS v12
        uses: actions/setup-node@v2
        with:
          node-version: 12.22.0
          cache: yarn

      - name: Install all dependencies
        run: yarn install

      - name: Check for ESlint errors
        run: yarn lint

      - name: Check for errors
        run: yarn build

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: guusvanmeerveld
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & Push
      - name: Build Dockerfile and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: guusvanmeerveld/argo-api:latest

          # Cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
